[build]
  command = "npm run netlify:build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/yahoo"
  to = "/.netlify/functions/yahoo"
  status = 200
