[build]
  base = "command_center"
  command = "npm run netlify:build"

[build.environment]
  PRISMA_SCHEMA_PATH = "prisma/schema.postgres.prisma"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/yahoo"
  to = "/.netlify/functions/yahoo"
  status = 200
