import { z } from "zod";

export const RYKAS_READ_CAPABILITY = "RYKAS_OPERATIONS_READ" as const;
export const rykasViewSchema = z.enum(["TOP", "OWNER_ACTION_NEEDED", "PURCHASE_READY", "NEEDS_DATA", "BLOCKED", "STALE_EVIDENCE"]);
const limit = z.number().int().min(1).max(25);
const asinSchema = z.string().regex(/^[A-Z0-9]{10}$/);
export const rykasReadRequestSchema = z.discriminatedUnion("operation", [
  z.object({ version: z.literal(1), operation: z.literal("OPERATIONS_SNAPSHOT"), input: z.object({ limit: limit.default(10) }).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("SOURCING_OPPORTUNITIES"), input: z.object({ view: rykasViewSchema, limit: limit.default(10) }).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("OPPORTUNITY_DETAIL"), input: z.object({ opportunityId: z.string().regex(/^US:[A-Z0-9]{10}$/) }).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("PURCHASE_CANDIDATES"), input: z.object({ limit: limit.default(10) }).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("OPERATIONS_BLOCKERS"), input: z.object({ limit: limit.default(10) }).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("FINANCIAL_SNAPSHOT"), input: z.object({}).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("CAPITAL_PLAN"), input: z.object({}).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("REPLENISHMENT_CANDIDATES"), input: z.object({ limit: limit.default(10) }).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("CAPITAL_RELEASE_CANDIDATES"), input: z.object({ limit: limit.default(10) }).strict() }).strict(),
  z.object({ version: z.literal(1), operation: z.literal("SALE_EVENT_EVALUATION"), input: z.object({ candidateIds: z.array(asinSchema).min(1).max(25) }).strict() }).strict()
]);
export type RykasReadRequest = z.infer<typeof rykasReadRequestSchema>;

const nullableNumber = z.number().finite().nullable();
const freshnessSchema = z.object({ observedAt: z.string().datetime(), authoritativeSource: z.string().min(1).max(500), sourceUpdatedAt: z.string().datetime().nullable(), classification: z.enum(["CURRENT", "STALE", "UNKNOWN"]), stale: z.boolean() }).strict();
export const rykasOpportunitySchema = z.object({
  opportunityId: z.string().regex(/^US:[A-Z0-9]{10}$/), asin: z.string().regex(/^[A-Z0-9]{10}$/), vendorSku: z.string().max(200).nullable(), brand: z.string().max(400).nullable(), title: z.string().max(1000).nullable(), supplier: z.string().max(500).nullable(),
  discoverySource: z.string().max(200).nullable(), discoveryStrategy: z.string().max(200).nullable(), currentBuyBox: nullableNumber, buyBox90: nullableNumber, observedOrReferenceCost: nullableNumber, maxLandedCost: nullableNumber, idealLandedCost: nullableNumber,
  profitPerUnit: nullableNumber, expectedProfit: nullableNumber, expectedMonthlyContribution: nullableNumber, roi: nullableNumber, margin: nullableNumber, estimatedMonthlyUnits: nullableNumber, units30: nullableNumber, units90: nullableNumber,
  sellerCount: z.number().int().nonnegative().nullable(), amazonOos90: nullableNumber, opportunityScore: nullableNumber, decision: z.string().max(80).nullable(), actionState: z.string().max(100), recommendationStatus: z.string().max(100).nullable(), recommendedUnits: z.number().int().nonnegative().nullable(), recommendedCases: nullableNumber, expectedSpend: nullableNumber,
  eligibilityStatus: z.string().max(100).nullable(), requiredAction: z.string().max(200).nullable(), sourceStatus: z.string().max(100).nullable(), reasonCodes: z.array(z.string().max(200)).max(100), missingEvidence: z.array(z.string().max(200)).max(50), blockers: z.array(z.string().max(500)).max(50), freshness: freshnessSchema
}).strict();

const blockerSchema = z.object({ id: z.string().max(200), opportunityId: z.string().max(50).nullable(), stage: z.enum(["OPPORTUNITY", "PURCHASE_DECISION", "INBOUND_INVENTORY", "LISTING", "SALE", "SYSTEM"]), code: z.string().max(200), summary: z.string().max(1000), sourceUpdatedAt: z.string().datetime().nullable(), stale: z.boolean() }).strict();
const capitalSchema = z.object({ reliable: z.boolean(), status: z.string().max(100), reason: z.string().max(2000).nullable(), actionRequired: z.string().max(1000).nullable(), asOf: z.string().nullable(), openCommitments: nullableNumber, purchaseOrderRows: z.number().int().nonnegative(), openPurchaseOrderLines: z.number().int().nonnegative(), poLedgerStatus: z.string().max(100), poCertificationState: z.string().max(100), poCertifiedAt: z.string().datetime().nullable(), poTruthCurrent: z.boolean(), safeInventoryCapital: nullableNumber }).strict();
const checklistItemSchema = z.object({ inputKey: z.string().max(100), status: z.enum(["CURRENT", "STALE", "MISSING", "CONFLICTING"]), observedAt: z.string().nullable(), freshnessDays: z.number().int().nonnegative().nullable(), authoritativeSource: z.string().max(500), reason: z.string().max(2000).nullable() }).strict();
const amazonCashForecastSchema = z.object({ amazonAvailableBalance: nullableNumber, amazonPendingBalance: nullableNumber, estimatedPayout7Days: nullableNumber, estimatedPayout14Days: nullableNumber, estimatedPayout30Days: nullableNumber, nextExpectedPayoutDate: z.string().nullable(), amazonReserveOrHold: nullableNumber, confidence: z.string().max(100), asOf: z.string(), missingInputs: z.array(z.string().max(200)).max(30) }).strict();
export const rykasCapitalPlanSchema = z.object({ schemaVersion: z.literal("RYKAS_CAPITAL_PLAN_V1"), status: z.enum(["READY", "BLOCKED"]), asOf: z.string(), settledCashOnly: z.literal(true), amazonForecastCountedAsSettledCash: z.literal(false), purchaseAuthorized: z.literal(false), purchaseExecuted: z.literal(false), debtPaymentAuthorized: z.literal(false), debtPaymentExecuted: z.literal(false), missingInputs: z.array(z.string().max(100)).max(30), blockers: z.array(z.string().max(2000)).max(30), grossCash: nullableNumber, forecastCash30Days: nullableNumber, committedCapital: nullableNumber, openObligations: nullableNumber, minimumDebtObligations: nullableNumber, debtPaymentBuffer: nullableNumber, operatingReserve: nullableNumber, coreReplenishmentReserve: nullableNumber, coreReplenishmentShortfall: nullableNumber, plannedExtraDebtReduction: nullableNumber, preliminaryFreeCapital: nullableNumber, safeBuyingCapacity: nullableNumber, coreReplenishmentBudget: nullableNumber, growthInventoryBudget: nullableNumber, opportunisticSaleBudget: nullableNumber, speculativeTestBudget: nullableNumber, remainingBuffer: nullableNumber, sources: z.array(z.record(z.unknown())).max(20) }).strict();
const financialSnapshotSchema = z.object({ schemaVersion: z.literal("RYKAS_FINANCIAL_SNAPSHOT_V1"), asOf: z.string(), status: z.enum(["READY", "BLOCKED"]), settledCash: z.object({ grossCash: z.number().finite(), forecastIncluded: z.literal(false) }).passthrough(), amazonCashForecast: amazonCashForecastSchema, commitments: z.object({ openPurchaseOrders: z.number().finite(), openLines: z.number().int().nonnegative(), asOf: z.string().nullable() }).strict(), obligations: z.object({ dueNext30Days: z.number().finite() }).passthrough(), debt: z.object({ totalBalance: z.number().finite(), minimumDueNext30Days: z.number().finite() }).passthrough(), ownerPolicy: z.record(z.unknown()), replenishment: z.object({ coreRequiredSpend: z.number().finite(), candidateCount: z.number().int().nonnegative() }).strict(), inventory: z.record(z.unknown()), performance: z.record(z.unknown()), checklist: z.array(checklistItemSchema).max(30), missingInputs: z.array(z.string().max(100)).max(30), capitalPlan: rykasCapitalPlanSchema, debtAdvice: z.record(z.unknown()), financialHealth: z.object({ status: z.string().max(100), reasons: z.array(z.string().max(2000)).max(10) }).strict(), weeklyCapitalPlan: z.record(z.unknown()), purchaseAuthorized: z.literal(false), purchaseExecuted: z.literal(false), debtPaymentAuthorized: z.literal(false), debtPaymentExecuted: z.literal(false) }).passthrough();
const replenishmentCandidateSchema = z.object({ asin: asinSchema, sellerSku: z.string().max(200).nullable(), title: z.string().max(1000).nullable(), vendor: z.string().max(500).nullable(), classification: z.enum(["CORE_REPLENISHMENT", "NORMAL", "TEST", "DO_NOT_REPLENISH"]), onHand: nullableNumber, inbound: nullableNumber, reserved: nullableNumber, committed: nullableNumber, dailyVelocity: nullableNumber, daysOfSupply: nullableNumber, estimatedStockoutDate: z.string().nullable(), leadTimeDays: nullableNumber, targetCoverageDays: nullableNumber, recommendedQuantity: nullableNumber, totalRequiredSpend: nullableNumber, expectedContribution: nullableNumber, recommendation: z.string().max(100), freshness: z.string().max(100).nullable(), missingInputs: z.array(z.string().max(1000)).max(20) }).strict();
const releaseCandidateSchema = z.object({ asin: asinSchema, sellerSku: z.string().max(200).nullable(), title: z.string().max(1000).nullable(), vendor: z.string().max(500).nullable(), units: nullableNumber, daysOfSupply: nullableNumber, inventoryCostTiedUp: nullableNumber, likelyCapitalFreed: nullableNumber, marginImpact: nullableNumber, recommendedAction: z.enum(["HOLD", "REPRICE", "BUNDLE", "LIQUIDATE", "DO_NOT_REPLENISH"]), reason: z.string().max(200).nullable(), freshness: z.string().max(100).nullable() }).strict();
const replenishmentResultSchema = z.object({ schemaVersion: z.literal("RYKAS_REPLENISHMENT_CANDIDATES_V1"), items: z.array(replenishmentCandidateSchema).max(25), purchaseExecuted: z.literal(false) }).strict();
const releaseResultSchema = z.object({ schemaVersion: z.literal("RYKAS_CAPITAL_RELEASE_CANDIDATES_V1"), items: z.array(releaseCandidateSchema).max(25), listingOrPriceChanged: z.literal(false), purchaseExecuted: z.literal(false) }).strict();
const saleEventResultSchema = z.object({ schemaVersion: z.literal("RYKAS_SALE_EVENT_EVALUATION_V1"), status: z.enum(["READY", "BLOCKED"]), safeEventBudget: nullableNumber, recommendedSpend: nullableNumber, candidates: z.array(z.record(z.unknown())).max(25), missingCandidateIds: z.array(asinSchema).max(25), purchaseAuthorized: z.literal(false), purchaseExecuted: z.literal(false) }).strict();
const actionSummarySchema = z.object({ action: z.string().max(100), count: z.number().int().nonnegative(), topOpportunityScore: nullableNumber }).strict();
const detailSchema = z.object({ opportunity: rykasOpportunitySchema, priceHistory: z.object({ buyBox30: nullableNumber, buyBox90: nullableNumber, buyBox180: nullableNumber }).strict(), competition: z.object({ offerCount30: nullableNumber, offerCount90: nullableNumber, offerCount180: nullableNumber }).strict(), inventory: z.object({ onHand: nullableNumber, reserved: nullableNumber, inbound: nullableNumber }).strict(), evidence: z.object({ evaluationVersion: z.string().max(200).nullable(), positives: z.array(z.string().max(1000)).max(50), risks: z.array(z.string().max(1000)).max(50), confidenceFactor: nullableNumber, priceConfidence: z.string().max(100).nullable(), availabilityConfidence: z.string().max(100).nullable(), priceAgeDays: z.number().int().nonnegative().nullable(), quantityStatus: z.string().max(100).nullable(), eligibilityCheckedAt: z.string().datetime().nullable(), marketCheckedAt: z.string().datetime().nullable(), buyBoxCheckedAt: z.string().datetime().nullable(), sourcePriceObservedAt: z.string().datetime().nullable() }).strict() }).strict();
const dataSchema = z.object({ actionSummary: z.array(actionSummarySchema).max(30).default([]), capital: capitalSchema.nullable().default(null), opportunities: z.array(rykasOpportunitySchema).max(25).default([]), purchaseCandidates: z.array(rykasOpportunitySchema).max(25).default([]), blockers: z.array(blockerSchema).max(25).default([]), detail: detailSchema.nullable().default(null), financialSnapshot: financialSnapshotSchema.nullable().default(null), capitalPlan: rykasCapitalPlanSchema.nullable().default(null), replenishmentCandidates: replenishmentResultSchema.nullable().default(null), capitalReleaseCandidates: releaseResultSchema.nullable().default(null), saleEventEvaluation: saleEventResultSchema.nullable().default(null) }).strict();
export const rykasTruthResultSchema = z.object({ schemaVersion: z.literal("RYKAS_TRUTH_READ_V1"), operation: z.enum(["OPERATIONS_SNAPSHOT", "SOURCING_OPPORTUNITIES", "OPPORTUNITY_DETAIL", "PURCHASE_CANDIDATES", "OPERATIONS_BLOCKERS", "FINANCIAL_SNAPSHOT", "CAPITAL_PLAN", "REPLENISHMENT_CANDIDATES", "CAPITAL_RELEASE_CANDIDATES", "SALE_EVENT_EVALUATION"]), readOnly: z.literal(true), purchaseAuthorized: z.literal(false), purchaseExecuted: z.literal(false), observedAt: z.string().datetime(), authoritativeSource: z.string().min(1).max(500), sourceUpdatedAt: z.string().datetime().nullable(), freshness: z.enum(["CURRENT", "STALE", "UNKNOWN"]), stale: z.boolean(), data: dataSchema }).strict();
export type RykasTruthResult = z.infer<typeof rykasTruthResultSchema>;
