import { z } from "zod";

export const RYKAS_OWNER_DATA_CAPABILITY = "RYKAS_OWNER_DATA_UPDATE" as const;
const money = z.number().finite().min(0).max(100_000_000);
const percent = z.number().finite().min(0).max(1);
const truthStatus = z.enum(["CURRENT_ROWS_LOADED", "CURRENT_NONE", "NOT_AVAILABLE", "NEEDS_RECONCILIATION"]);
const debt = z.object({ displayName: z.string().min(1).max(160), debtType: z.string().min(1).max(60).default("OTHER"), currentBalance: money, apr: percent.nullable(), minimumPayment: money.nullable(), nextDueDate: z.string().date().nullable(), promotionalRateEnd: z.string().date().nullable(), ownerPriority: z.number().int().min(1).max(100).nullable().default(null), notes: z.string().max(1000).nullable() }).strict();
const obligation = z.object({ vendor: z.string().max(200).nullable(), description: z.string().min(1).max(1000), amountDue: money.positive(), dueDate: z.string().date(), category: z.string().min(1).max(80), relatedPurchaseOrderId: z.number().int().positive().nullable() }).strict();
export const rykasOwnerFinancialUpdateSchema = z.object({ version: z.literal(1), observedAt: z.string().datetime(), businessCash: z.object({ label: z.string().min(1).max(120).default("Rykas operating cash"), amount: money }).strict().nullable(), debts: z.object({ status: truthStatus, items: z.array(debt).max(20), note: z.string().max(1000).nullable() }).strict().nullable(), obligations: z.object({ status: truthStatus, items: z.array(obligation).max(25), note: z.string().max(1000).nullable() }).strict().nullable(), ownerPolicy: z.object({ minimumOperatingReserve: money, minimumDebtPaymentBuffer: money.nullable(), desiredMonthlyExtraDebtPayment: money.nullable(), percentOfExcessCashToDebt: percent.nullable(), maximumDiscretionaryInventoryPercent: percent, maximumBrandConcentrationPercent: percent.nullable(), coreReplenishmentPriority: z.string().max(40).nullable(), speculativeTestBudgetCap: money.nullable(), debtStrategy: z.enum(["HIGHEST_APR", "OWNER_DEFINED_ORDER"]), notes: z.string().max(1000).nullable() }).strict().nullable(), poCertification: z.enum(["CURRENT_NO_OPEN_POS", "CURRENT_OPEN_POS_LOADED"]).nullable() }).strict();
export type RykasOwnerFinancialUpdate = z.infer<typeof rykasOwnerFinancialUpdateSchema>;
export const rykasOwnerFinancialUpdateResultSchema = z.object({ schemaVersion: z.literal("RYKAS_OWNER_FINANCIAL_TRUTH_UPDATE_V1"), status: z.literal("SAVED"), writes: z.object({ businessCash: z.number().int().nonnegative(), debts: z.number().int().nonnegative(), obligations: z.number().int().nonnegative(), ownerPolicy: z.number().int().nonnegative(), poCertification: z.number().int().nonnegative() }).strict(), observedAt: z.string().datetime(), purchaseAuthorized: z.literal(false), purchaseExecuted: z.literal(false), debtPaymentAuthorized: z.literal(false), debtPaymentExecuted: z.literal(false), financialCommitmentCreated: z.literal(false) }).strict();
